USE AGENDA;

CREATE TABLE USUARIO (
 ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(45),
 EMAIL VARCHAR(100) UNIQUE,
 SENHA VARCHAR(255),
 ALTERNATIVA VARCHAR(45),
 RESPOSTA VARCHAR(45)
);

CREATE TABLE CONTATO (
 ID_CONTATO INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(45),
 TELEFONE VARCHAR(45),
 EMAIL VARCHAR(45),
 ID_USUARIO INT,
 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
